package com.ironhack.bookmark_app.enums;

public enum CommandType {
    EXIT,
    HELP,
    NEW_USER,
    SHOW_USERS,
    LOOKUP_USER,
    SHOW_BOOKS,
    LOOKUP_BOOK,
    SEARCH_BOOK,
    USERS_BY_BOOK,
    ASSIGN_BOOK_TO_USER,
    USERS_TO_READ_BY_BOOK,
    USERS_READING_BY_BOOK,
    USERS_READ_BY_BOOK,
    BOOKS_BY_USER,
    BOOKS_TO_READ_BY_USER,
    BOOKS_READING_BY_USER,
    BOOKS_READ_BY_USER,
    REMOVE_FAVOURITE, STATUS_BOOKS_USER

}
